{
    "name": "Login as Omydoo",
    "summary": "Ouverture d'une session Odoo par jeton signé, pilotée par le tableau de bord Omydoo.",
    "version": "15.0.1.0.0",
    "author": "Omydoo",
    "website": "https://www.omydoo.fr",
    "license": "LGPL-3",
    "category": "Tools",
    "depends": ["base", "web"],
    "external_dependencies": {"python": ["cryptography"]},
    "data": ["security/ir.model.access.csv"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
